// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCardData(arg1) {
  return window['go']['main']['App']['DeleteCardData'](arg1);
}

export function GetCardData() {
  return window['go']['main']['App']['GetCardData']();
}

export function SaveCardData(arg1) {
  return window['go']['main']['App']['SaveCardData'](arg1);
}

export function SaveCardPNG(arg1, arg2) {
  return window['go']['main']['App']['SaveCardPNG'](arg1, arg2);
}

export function UpdateCardData(arg1, arg2) {
  return window['go']['main']['App']['UpdateCardData'](arg1, arg2);
}
