// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteCardData(arg1:string):Promise<void>;

export function GetCardData():Promise<Array<main.CardData>>;

export function SaveCardData(arg1:main.SaveCardDataRequest):Promise<string>;

export function SaveCardPNG(arg1:string,arg2:Array<number>):Promise<void>;

export function UpdateCardData(arg1:string,arg2:main.UpdateCardDataRequest):Promise<void>;
